server:
  port: 8082

spring:
  application:
    name: pricing-service-kotlin
  datasource:
    url: jdbc:h2:mem:pricingkotlin;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  health:
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

app:
  cache:
    redis-enabled: false
    ttl-seconds: 180
