spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/retail_pricing
    username: retail
    password: retail
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false

management:
  health:
    redis:
      enabled: true

app:
  cache:
    redis-enabled: true
